spring:
  cloud:
    # Nacos 注册中心
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 192.168.30.180:8848
        namespace: a03fbe75-bfcf-4d9e-b848-5da01fc74201
  # sharding jdbc
  shardingsphere:
    enabled: true
    datasource:
      name: master
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.30.180:3201/cluster_db1?allowMultiQueries=true&useSSL=false&characterEncoding=utf8
        username: db_cluster
        password: db123
#    props:
#      # 开启SQL显示
#      sql:
#        show: true

# Mybatis Plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.lmaye.micros.service.user.entity.*
  global-config:
    db-config:
      id-type: id_worker
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      table-underline: true
      capital-mode: true
  type-handlers-package: com.lmaye.micros.starter.mybatis.type
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  config: classpath:log4j2-dev.xml