# 服务端口
server:
  port: 8300

# Spring 配置
spring:
  application:
    name: micros-user
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    # sdt: 读写分离 + 分表分库
    # sms: 读写分离
    # sin: 单库
    active: sin